---
name: CI pipeline

on:
  pull_request:
  push:
    branches: [main]
    tags: ['v*.*.*']
  workflow_dispatch:

env:
  IMAGE: ghcr.io/kadykov/fontbyte:latest
  OUTPUT_DIR: public
  OUTPUT_ARTIFACTS_NAME: website

jobs:
  pre_commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit-ci/lite-action@v1.0.3
        if: always()

  docker:
    name: Build and push testing Docker image
    needs: pre_commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE }}
          cache-from: type=registry,ref=${{ env.IMAGE }}
          cache-to: type=inline

      - name: Render with Docker image
        run: >
          docker container run
          -v "${PWD}:/data"
          --user "$(id -u):$(id -g)"
          -e "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
          ${{ env.IMAGE }}

      - run: mkdir -p ./${{ env.OUTPUT_DIR }} && cp ./*.html ./${{ env.OUTPUT_DIR }}

      - name: Upload rendered artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_ARTIFACTS_NAME }}
          path: ./${{ env.OUTPUT_DIR }}
          if-no-files-found: error

  publish:
    name: Publish to GitHub pages
    needs: docker
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.OUTPUT_ARTIFACTS_NAME }}
          path: ${{ env.OUTPUT_DIR }}/

      - name: Deploy CV to GitHub pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ env.OUTPUT_DIR }}
